# Generated by Django 2.0.9 on 2019-03-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='defo', upload_to='blog/'),
        ),
    ]
