# Generated by Django 2.0.9 on 2019-03-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190320_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='defo/donmai.png', upload_to='blog/'),
        ),
    ]
