# Generated by Django 2.0.9 on 2019-03-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190320_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='blog/donmai.png', upload_to='blog/'),
        ),
    ]
